experiment_name: experiment_test
languages:
  en:
    language: en
    path_to_conll_dataset: UD_English-GUM/en_gum-ud-train.conllu
    models:
    - meta-llama/Llama-3.2-1B
multilingual_models: []
min_words_matching_relation: 0
trim_dataset_size: 100 # Minimum size across datasets: 1K (TreeGal)
# group_relations_by_family: true
# accept_bidirectional_relations: true
