experiment_name: experiment_test
languages:
  en:
    language: en
    path_to_conll_dataset: UD_English-GUM/en_gum-ud-train.conllu
    models: []
multilingual_models:
- google-bert/bert-base-uncased
- openai-community/gpt2
min_words_matching_relation: 20
trim_dataset_size: 1000 # Minimum size across datasets: 1K (TreeGal)
# group_relations_by_family: true
# accept_bidirectional_relations: true
